# Generated by Django 5.0.2 on 2024-04-27 10:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
                ('slug', models.CharField(db_index=True, default=uuid.uuid4, max_length=150, unique=True, verbose_name='Ссылка')),
                ('author', models.CharField(db_index=True, max_length=150, verbose_name='Автор')),
                ('cover_image', models.ImageField(blank=True, upload_to='bookstore/static/bookstore/img/covers/%Y/%m/%d', verbose_name='Обложка')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Рейтинг')),
                ('published_date', models.DateField(verbose_name='Дата публикации')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.section')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ('title',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
