# Generated by Django 5.0.2 on 2024-04-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='books/img/covers/%Y/%m/%d', verbose_name='Обложка'),
        ),
    ]
